psql -c "alter user postgres password 'postgres'"
psql -c "create database piweatherstation"
psql piweatherstation -c "create table sensors (t_sensor_type varchar(12) primary key)"
psql piweatherstation -c "insert into sensors (t_sensor_type) values (temperature),(humidity),(pressure),(air quality)"
psql piweatherstation -c "create table temperature (ts_collection_time timestamp primary key, i_temperature_value smallint)"
psql piweatherstation -c "create table humidity (ts_collection_time timestamp primary key, i_humidity_value smallint)"
psql piweatherstation -c "create table pressure (ts_collection_time timestamp primary key, i_pressure_value smallint)"
psql piweatherstation -c "create table air_quality (ts_collection_time timestamp primary key, i_aq_value smallint)"
psql piweatherstation -c "create table daily_averages (ts_time_computed timestamp primary key, i_temperature_avg smallint, i_humidity_avg smallint, i_pressure_avg smallint, i_aq_avg smallint)"
psql piweatherstation -c "create table weekly_averages (date_beginned_on date primary key, date_ended_on date, i_temperature_avg smallint, i_humidity_avg smallint, i_pressure_avg smallint, i_aq_avg smallint)"
psql piweatherstation -c "create table monthly_averages (date_month_computed date primary key, i_temperature_avg smallint, i_humidity_avg smallint, i_pressure_avg smallint, i_aq_avg smallint)"
